#!/usr/bin/env python3
"""Regenerate data/sw-colors.js and data/sw-colors-full.js from colorswatches.xlsx.

- data/sw-colors-full.js  -> window.SW_COLORS_FULL, every SW color in the dump.
- data/sw-colors.js       -> window.SW_COLORS / window.SW_GROUPS, the curated
                             exterior palette (codes + groups from
                             data/sw-curated.json), with name and hex
                             overwritten by the authoritative xlsx values.

Run whenever colorswatches.xlsx is updated or curated codes change.
"""

import json
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

HERE = Path(__file__).resolve().parent
XLSX = HERE / "colorswatches.xlsx"
CURATED_JSON = HERE / "data" / "sw-curated.json"
FULL_JS = HERE / "data" / "sw-colors-full.js"
CURATED_JS = HERE / "data" / "sw-colors.js"

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"


def load_dump():
    with zipfile.ZipFile(XLSX) as z:
        ss_xml = z.read("xl/sharedStrings.xml").decode("utf-8")
        sheet_xml = z.read("xl/worksheets/sheet1.xml").decode("utf-8")

    strings = []
    for si in ET.fromstring(ss_xml).iter(NS + "si"):
        strings.append("".join(n.text or "" for n in si.iter(NS + "t")))

    rows = {}
    for row in ET.fromstring(sheet_xml).iter(NS + "row"):
        r_idx = int(row.get("r"))
        cells = {}
        for c in row.findall(NS + "c"):
            ref = c.get("r")
            col = "".join(ch for ch in ref if ch.isalpha())
            v = c.find(NS + "v")
            val = v.text if v is not None else None
            if c.get("t") == "s" and val is not None:
                val = strings[int(val)]
            cells[col] = val
        rows[r_idx] = cells

    dump = {}
    for r in sorted(rows):
        code = rows[r].get("A")
        if not code or not re.match(r"^SW\d+$", code):
            continue
        dump[code] = {
            "code": code,
            "name": rows[r].get("B") or "",
            "hex": (rows[r].get("G") or "").upper(),
            "locator": rows[r].get("C") or "",
        }
    return dump


def js_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_full(dump):
    lines = [
        "// Auto-generated by build-sw-colors.py from colorswatches.xlsx.",
        "// Do not edit by hand.",
        "window.SW_COLORS_FULL = [",
    ]
    for code in sorted(dump, key=lambda c: int(c[2:])):
        e = dump[code]
        lines.append(
            f'  {{ code: "{e["code"]}", name: "{js_escape(e["name"])}", '
            f'hex: "#{e["hex"]}", locator: "{js_escape(e["locator"])}" }},'
        )
    lines.append("];")
    lines.append("")
    FULL_JS.write_text("\n".join(lines))


def write_curated(dump):
    src = json.loads(CURATED_JSON.read_text())
    curated_codes = src["colors"]
    group_order = src["groups"]

    missing = []
    resolved = []
    for entry in curated_codes:
        code = entry["code"].replace(" ", "").upper()
        group = entry["group"]
        row = dump.get(code)
        if not row:
            missing.append(code)
            continue
        resolved.append({
            "code": row["code"],
            "name": row["name"],
            "hex": row["hex"],
            "group": group,
        })

    by_group = {}
    for c in resolved:
        by_group.setdefault(c["group"], []).append(c)

    lines = [
        "// Auto-generated by build-sw-colors.py from colorswatches.xlsx + data/sw-curated.json.",
        "// Do not edit by hand. To change which codes appear or how they are grouped,",
        "// edit data/sw-curated.json.",
        "//",
        "// Hex values and names come straight from Sherwin-Williams' published dump, so",
        "// they match the manufacturer's own color data. Real paint on real siding under",
        "// real light will still differ — order chips before committing.",
        "window.SW_COLORS = [",
    ]
    for group in group_order:
        if group not in by_group:
            continue
        lines.append(f"  // {group}")
        for c in by_group[group]:
            lines.append(
                f'  {{ code: "{c["code"]}", name: "{js_escape(c["name"])}", '
                f'hex: "#{c["hex"]}", group: "{js_escape(c["group"])}" }},'
            )
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("];")
    lines.append("")
    lines.append("window.SW_GROUPS = [")
    for g in group_order:
        lines.append(f'  "{js_escape(g)}",')
    lines.append("];")
    lines.append("")
    CURATED_JS.write_text("\n".join(lines))

    return resolved, missing


def main():
    if not XLSX.exists():
        sys.exit(f"missing {XLSX}")
    if not CURATED_JSON.exists():
        sys.exit(f"missing {CURATED_JSON}")

    dump = load_dump()
    print(f"loaded {len(dump)} SW colors from {XLSX.name}")

    write_full(dump)
    print(f"wrote {FULL_JS.relative_to(HERE)} ({len(dump)} colors)")

    resolved, missing = write_curated(dump)
    print(
        f"wrote {CURATED_JS.relative_to(HERE)} "
        f"({len(resolved)} curated colors across {len({c['group'] for c in resolved})} groups)"
    )
    if missing:
        print()
        print(f"WARNING: {len(missing)} curated code(s) not found in dump; dropped:")
        for code in missing:
            print(f"  - {code}")


if __name__ == "__main__":
    main()
